#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##################### Configuration of 'userdb' by group sharding v5 #######################

# External logical database schema.
schemaName: userdb

# Default datasource configuration.
# @see:org.apache.shardingsphere.proxy.config.ProxyConfigurationLoader#loadRuleConfiguration
dataSource:
  username: root
  #password: 'zzx!@#$%'
  password: root
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50
  minPoolSize: 1
  maintenanceIntervalMilliseconds: 30000

# Datasource configuration.
dataSources:
  #userdb_g0db0_schema:
  #  url: jdbc:mysql://127.0.0.1:3306/information_schema?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8
  userdb_g0db0:
    url: jdbc:mysql://127.0.0.1:13306/userdb_g0db0?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8
  userdb_g0db1:
    url: jdbc:mysql://127.0.0.1:13307/userdb_g0db1?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8
  userdb_g0db2:
    url: jdbc:mysql://127.0.0.1:13308/userdb_g0db2?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8
#  userdb_g1db0:
#    url: jdbc:mysql://127.0.0.1:13306/userdb_g1db0?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8
#  userdb_g1db1:
#    url: jdbc:mysql://127.0.0.1:13307/userdb_g1db1?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8
#  userdb_g1db2:
#    url: jdbc:mysql://127.0.0.1:13308/userdb_g1db2?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8

# Schema rule configuration.
rules:
 - !READWRITE_SPLITTING
  dataSources:
    rw_userdb_g0db0:
      writeDataSourceName: userdb_g0db0
      readDataSourceNames:
        - userdb_g0db1
        - userdb_g0db2
      loadBalancerName: randomBalancer1
  loadBalancers:
    randomBalancer1:
      type: RANDOM

